# Generated by Django 5.1.2 on 2024-10-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('category', models.CharField(choices=[('expecting_a_baby', 'Expecting a Baby'), ('new_parents', 'New Parents'), ('preschool_primary_school', 'Preschool and Primary School'), ('secondary_school', 'Secondary School'), ('young_people', 'Young People'), ('adults', 'Adults')], max_length=30)),
                ('advice', models.TextField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('category', models.CharField(choices=[('expecting_a_baby', 'Expecting a Baby'), ('new_parents', 'New Parents'), ('preschool_primary_school', 'Preschool and Primary School'), ('secondary_school', 'Secondary School'), ('young_people', 'Young People'), ('adults', 'Adults')], max_length=30)),
                ('therapy_content', models.TextField()),
                ('advice', models.TextField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
