# Generated by Django 5.1.2 on 2024-10-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_journal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='journal',
        ),
    ]
