# Generated by Django 5.1.2 on 2024-10-17 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('expecting_a_baby', 'Expecting a Baby'), ('new_parents', 'New Parents'), ('preschool_primary_school', 'Preschool and Primary School'), ('secondary_school', 'Secondary School'), ('young_people', 'Young People'), ('adults', 'Adults')], max_length=30)),
                ('advice', models.TextField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('expecting_a_baby', 'Expecting a Baby'), ('new_parents', 'New Parents'), ('preschool_primary_school', 'Preschool and Primary School'), ('secondary_school', 'Secondary School'), ('young_people', 'Young People'), ('adults', 'Adults')], max_length=30)),
                ('therapy_content', models.TextField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('time', models.DateTimeField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parent')),
            ],
        ),
    ]
