# Generated by Django 5.1.2 on 2024-10-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_advice_therapysession_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
